from EventExploreServer.component.elasticsearch.search import search_articles
from EventExploreServer.component.open_relation_extraction.extract import extract
from EventExploreServer.component.word_link.WordGraph import WordGraph